export type PresenteInicial = { name: string; desired: number; unit: string };

export const presentesIniciais: PresenteInicial[] = [
  { name: 'Abridor de lata', desired: 1, unit: 'Item' },
  { name: 'Açucareiro', desired: 1, unit: 'Item' },
  { name: 'Afiador de facas', desired: 1, unit: 'Item' },
  { name: 'Air fryer', desired: 1, unit: 'Item' },
  { name: 'Aspirador vertical', desired: 1, unit: 'Item' },
  { name: 'Avental', desired: 2, unit: 'Item' },
  { name: 'Batedeira', desired: 1, unit: 'Item' },
  { name: 'Bule de café', desired: 1, unit: 'Item' },
  { name: 'Chaleira', desired: 1, unit: 'Item' },
  { name: 'Chaleira elétrica', desired: 1, unit: 'Item' },
  { name: 'Coador', desired: 1, unit: 'Item' },
  { name: 'Colher de pau', desired: 2, unit: 'Kit' },
  { name: 'Colher de sorvete', desired: 1, unit: 'Item' },
  { name: 'Concha', desired: 1, unit: 'Item' },
  { name: 'Conjunto de xícaras', desired: 2, unit: 'Item' },
  { name: 'Conjunto para sobremesa', desired: 2, unit: 'Item' },
  { name: 'Copo de medida', desired: 1, unit: 'Item' },
  { name: 'Cortador de queijo', desired: 1, unit: 'Item' },
  { name: 'Descanso de panelas', desired: 2, unit: 'Kit' },
  { name: 'Escorredor de louça', desired: 1, unit: 'Item' },
  { name: 'Escorredor de macarrão', desired: 1, unit: 'Item' },
  { name: 'Escumadeira', desired: 2, unit: 'Item' },
  { name: 'Espremedor', desired: 1, unit: 'Item' },
  { name: 'Faca de pão', desired: 2, unit: 'Item' },
  { name: 'Formas e assadeiras', desired: 2, unit: 'Kit' },
  { name: 'Frigideira', desired: 3, unit: 'Item' },
  { name: 'Garrafa térmica', desired: 2, unit: 'Item' },
  { name: 'Jarra', desired: 3, unit: 'Item' },
  { name: 'Jogo americano', desired: 2, unit: 'Item' },
  { name: 'Jogo de copos', desired: 2, unit: 'Item' },
  { name: 'Jogo de faca', desired: 2, unit: 'Item' },
  { name: 'Jogo de panelas', desired: 2, unit: 'Item' },
  { name: 'Jogo de pratos', desired: 2, unit: 'Item' },
  { name: 'Jogo de Talheres', desired: 2, unit: 'Item' },
  { name: 'Jogo de utensílios silicone', desired: 2, unit: 'Item' },
  { name: 'Leiteira', desired: 2, unit: 'Item' },
  { name: 'Liquidificador', desired: 1, unit: 'Item' },
  { name: 'Lixeiras de cozinha', desired: 2, unit: 'Item' },
  { name: 'Luva térmica', desired: 1, unit: 'Item' },
  { name: 'Manteigueira', desired: 1, unit: 'Item' },
  { name: 'Marinex', desired: 3, unit: 'Item' },
  { name: 'Pá de lixo', desired: 1, unit: 'Item' },
  { name: 'Panela de pressão', desired: 1, unit: 'Item' },
  { name: 'Pano de chão', desired: 5, unit: 'Item' },
  { name: 'Panos de prato', desired: 20, unit: 'Item' },
  { name: 'Pegador de macarrão', desired: 3, unit: 'Item' },
  { name: 'Peneira', desired: 3, unit: 'Item' },
  { name: 'Porta condimentos', desired: 2, unit: 'Kit' },
  { name: 'Porta detergente e esponja', desired: 1, unit: 'Item' },
  { name: 'Porta frios', desired: 1, unit: 'Item' },
  { name: 'Porta papel toalha', desired: 1, unit: 'Item' },
  { name: 'Porta tempero', desired: 1, unit: 'Item' },
  { name: 'Pote hermético', desired: 2, unit: 'Kit' },
  { name: 'Potes multiuso', desired: 2, unit: 'Kit' },
  { name: 'Ralador', desired: 2, unit: 'Item' },
  { name: 'Rodinho de pia', desired: 1, unit: 'Item' },
  { name: 'Saca rolhas', desired: 1, unit: 'Item' },
  { name: 'Saleiro', desired: 1, unit: 'Item' },
  { name: 'Tábua para cortes', desired: 3, unit: 'Item' },
  { name: 'Toalha de mesa', desired: 3, unit: 'Item' },
  { name: 'Torradeira', desired: 1, unit: 'Item' },
  { name: 'Cortina para sala', desired: 1, unit: 'Item' },
  { name: 'Almofadas', desired: 2, unit: 'Kit' },
  { name: 'Mantas', desired: 2, unit: 'Item' },
  { name: 'Tapete', desired: 1, unit: 'Item' },
  { name: 'Cesto para roupa retangular', desired: 2, unit: 'Item' },
  { name: 'Escova para vaso sanitário', desired: 1, unit: 'Item' },
  { name: 'Lixeira', desired: 1, unit: 'Item' },
  { name: 'Porta escova de dentes', desired: 1, unit: 'Item' },
  { name: 'Roupão', desired: 2, unit: 'Item' },
  { name: 'Saboneteira', desired: 1, unit: 'Item' },
  { name: 'Tapete antiaderente para box', desired: 1, unit: 'Item' },
  { name: 'Toalhas de banho', desired: 8, unit: 'Item' },
  { name: 'Toalhas de rosto', desired: 10, unit: 'Item' },
  { name: 'Cabides', desired: 3, unit: 'Kit' },
  { name: 'Cobertor', desired: 3, unit: 'Kit' },
  { name: 'Edredons', desired: 2, unit: 'Item' },
  { name: 'Jogo de cama', desired: 10, unit: 'Item' },
  { name: 'Tapete para quarto', desired: 2, unit: 'Item' },
  { name: 'Travesseiro', desired: 4, unit: 'Item' },
  { name: 'Baldes de plástico', desired: 3, unit: 'Item' },
  { name: 'Escovinha de limpeza', desired: 1, unit: 'Item' },
  { name: 'Esfregão', desired: 1, unit: 'Item' },
  { name: 'Porta sabão', desired: 2, unit: 'Item' },
  { name: 'Pregadores de roupa', desired: 3, unit: 'Kit' },
  { name: 'Rodo', desired: 1, unit: 'Item' },
  { name: 'Rodo mop', desired: 1, unit: 'Item' },
  { name: 'Varal de chão', desired: 1, unit: 'Item' },
  { name: 'Vassouras', desired: 1, unit: 'Item' },
];
