-- Unidade do presente (Item, Kit, etc.) e carga da lista inicial.

ALTER TABLE public.gifts
  ADD COLUMN IF NOT EXISTS unit text NOT NULL DEFAULT 'Item';

ALTER TABLE public.gifts
  DROP CONSTRAINT IF EXISTS gifts_unit_len;
ALTER TABLE public.gifts
  ADD CONSTRAINT gifts_unit_len CHECK (char_length(unit) BETWEEN 1 AND 30);

INSERT INTO public.gifts (name, desired_quantity, unit)
SELECT v.name, v.desired_quantity, v.unit
FROM (VALUES
  ('Abridor de lata', 1, 'Item'),
  ('Açucareiro', 1, 'Item'),
  ('Afiador de facas', 1, 'Item'),
  ('Air fryer', 1, 'Item'),
  ('Aspirador vertical', 1, 'Item'),
  ('Avental', 2, 'Item'),
  ('Batedeira', 1, 'Item'),
  ('Bule de café', 1, 'Item'),
  ('Chaleira', 1, 'Item'),
  ('Chaleira elétrica', 1, 'Item'),
  ('Coador', 1, 'Item'),
  ('Colher de pau', 2, 'Kit'),
  ('Colher de sorvete', 1, 'Item'),
  ('Concha', 1, 'Item'),
  ('Conjunto de xícaras', 2, 'Item'),
  ('Conjunto para sobremesa', 2, 'Item'),
  ('Copo de medida', 1, 'Item'),
  ('Cortador de queijo', 1, 'Item'),
  ('Descanso de panelas', 2, 'Kit'),
  ('Escorredor de louça', 1, 'Item'),
  ('Escorredor de macarrão', 1, 'Item'),
  ('Escumadeira', 2, 'Item'),
  ('Espremedor', 1, 'Item'),
  ('Faca de pão', 2, 'Item'),
  ('Formas e assadeiras', 2, 'Kit'),
  ('Frigideira', 3, 'Item'),
  ('Garrafa térmica', 2, 'Item'),
  ('Jarra', 3, 'Item'),
  ('Jogo americano', 2, 'Item'),
  ('Jogo de copos', 2, 'Item'),
  ('Jogo de faca', 2, 'Item'),
  ('Jogo de panelas', 2, 'Item'),
  ('Jogo de pratos', 2, 'Item'),
  ('Jogo de Talheres', 2, 'Item'),
  ('Jogo de utensílios silicone', 2, 'Item'),
  ('Leiteira', 2, 'Item'),
  ('Liquidificador', 1, 'Item'),
  ('Lixeiras de cozinha', 2, 'Item'),
  ('Luva térmica', 1, 'Item'),
  ('Manteigueira', 1, 'Item'),
  ('Marinex', 3, 'Item'),
  ('Pá de lixo', 1, 'Item'),
  ('Panela de pressão', 1, 'Item'),
  ('Pano de chão', 5, 'Item'),
  ('Panos de prato', 20, 'Item'),
  ('Pegador de macarrão', 3, 'Item'),
  ('Peneira', 3, 'Item'),
  ('Porta condimentos', 2, 'Kit'),
  ('Porta detergente e esponja', 1, 'Item'),
  ('Porta frios', 1, 'Item'),
  ('Porta papel toalha', 1, 'Item'),
  ('Porta tempero', 1, 'Item'),
  ('Pote hermético', 2, 'Kit'),
  ('Potes multiuso', 2, 'Kit'),
  ('Ralador', 2, 'Item'),
  ('Rodinho de pia', 1, 'Item'),
  ('Saca rolhas', 1, 'Item'),
  ('Saleiro', 1, 'Item'),
  ('Tábua para cortes', 3, 'Item'),
  ('Toalha de mesa', 3, 'Item'),
  ('Torradeira', 1, 'Item'),
  ('Cortina para sala', 1, 'Item'),
  ('Almofadas', 2, 'Kit'),
  ('Mantas', 2, 'Item'),
  ('Tapete', 1, 'Item'),
  ('Cesto para roupa retangular', 2, 'Item'),
  ('Escova para vaso sanitário', 1, 'Item'),
  ('Lixeira', 1, 'Item'),
  ('Porta escova de dentes', 1, 'Item'),
  ('Roupão', 2, 'Item'),
  ('Saboneteira', 1, 'Item'),
  ('Tapete antiaderente para box', 1, 'Item'),
  ('Toalhas de banho', 8, 'Item'),
  ('Toalhas de rosto', 10, 'Item'),
  ('Cabides', 3, 'Kit'),
  ('Cobertor', 3, 'Kit'),
  ('Edredons', 2, 'Item'),
  ('Jogo de cama', 10, 'Item'),
  ('Tapete para quarto', 2, 'Item'),
  ('Travesseiro', 4, 'Item'),
  ('Baldes de plástico', 3, 'Item'),
  ('Escovinha de limpeza', 1, 'Item'),
  ('Esfregão', 1, 'Item'),
  ('Porta sabão', 2, 'Item'),
  ('Pregadores de roupa', 3, 'Kit'),
  ('Rodo', 1, 'Item'),
  ('Rodo mop', 1, 'Item'),
  ('Varal de chão', 1, 'Item'),
  ('Vassouras', 1, 'Item')
) AS v(name, desired_quantity, unit)
WHERE NOT EXISTS (SELECT 1 FROM public.gifts LIMIT 1);
